version: '2'

services:
  db:
    image: mariadb:10.11
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/transactions.sql
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  web:
    image: php:8.2-apache-bookworm
    depends_on:
      - db
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "${HTTP_PORT}:80"
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    command:
      - /bin/sh
      - -c
      - |
        docker-php-ext-install mysqli
        docker-php-ext-enable mysqli
        echo "MySQLi extension installed..."
        exec docker-php-entrypoint apache2-foreground
    stdin_open: true
    tty: true

